// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: internal/ocr/proto/ocr.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExtractRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FilePath      string                 `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	FileType      string                 `protobuf:"bytes,3,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractRequest) Reset() {
	*x = ExtractRequest{}
	mi := &file_internal_ocr_proto_ocr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractRequest) ProtoMessage() {}

func (x *ExtractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ocr_proto_ocr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractRequest.ProtoReflect.Descriptor instead.
func (*ExtractRequest) Descriptor() ([]byte, []int) {
	return file_internal_ocr_proto_ocr_proto_rawDescGZIP(), []int{0}
}

func (x *ExtractRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExtractRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *ExtractRequest) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

type ExtractResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractResponse) Reset() {
	*x = ExtractResponse{}
	mi := &file_internal_ocr_proto_ocr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractResponse) ProtoMessage() {}

func (x *ExtractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ocr_proto_ocr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractResponse.ProtoReflect.Descriptor instead.
func (*ExtractResponse) Descriptor() ([]byte, []int) {
	return file_internal_ocr_proto_ocr_proto_rawDescGZIP(), []int{1}
}

func (x *ExtractResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_internal_ocr_proto_ocr_proto protoreflect.FileDescriptor

const file_internal_ocr_proto_ocr_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/ocr/proto/ocr.proto\x12\x03ocr\"Z\n" +
	"\x0eExtractRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\x12\x1b\n" +
	"\tfile_type\x18\x03 \x01(\tR\bfileType\"%\n" +
	"\x0fExtractResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text2E\n" +
	"\tOCREngine\x128\n" +
	"\vExtractText\x12\x13.ocr.ExtractRequest\x1a\x14.ocr.ExtractResponseB(Z&SebasXeon/Fileoteca/internal/ocr/protob\x06proto3"

var (
	file_internal_ocr_proto_ocr_proto_rawDescOnce sync.Once
	file_internal_ocr_proto_ocr_proto_rawDescData []byte
)

func file_internal_ocr_proto_ocr_proto_rawDescGZIP() []byte {
	file_internal_ocr_proto_ocr_proto_rawDescOnce.Do(func() {
		file_internal_ocr_proto_ocr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_ocr_proto_ocr_proto_rawDesc), len(file_internal_ocr_proto_ocr_proto_rawDesc)))
	})
	return file_internal_ocr_proto_ocr_proto_rawDescData
}

var file_internal_ocr_proto_ocr_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_ocr_proto_ocr_proto_goTypes = []any{
	(*ExtractRequest)(nil),  // 0: ocr.ExtractRequest
	(*ExtractResponse)(nil), // 1: ocr.ExtractResponse
}
var file_internal_ocr_proto_ocr_proto_depIdxs = []int32{
	0, // 0: ocr.OCREngine.ExtractText:input_type -> ocr.ExtractRequest
	1, // 1: ocr.OCREngine.ExtractText:output_type -> ocr.ExtractResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_ocr_proto_ocr_proto_init() }
func file_internal_ocr_proto_ocr_proto_init() {
	if File_internal_ocr_proto_ocr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_ocr_proto_ocr_proto_rawDesc), len(file_internal_ocr_proto_ocr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_ocr_proto_ocr_proto_goTypes,
		DependencyIndexes: file_internal_ocr_proto_ocr_proto_depIdxs,
		MessageInfos:      file_internal_ocr_proto_ocr_proto_msgTypes,
	}.Build()
	File_internal_ocr_proto_ocr_proto = out.File
	file_internal_ocr_proto_ocr_proto_goTypes = nil
	file_internal_ocr_proto_ocr_proto_depIdxs = nil
}
