// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.31.1
// source: ocr.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OCREngine_ExtractText_FullMethodName       = "/ocr.OCREngine/ExtractText"
	OCREngine_GenerateThumbnail_FullMethodName = "/ocr.OCREngine/GenerateThumbnail"
)

// OCREngineClient is the client API for OCREngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OCREngineClient interface {
	ExtractText(ctx context.Context, in *ExtractRequest, opts ...grpc.CallOption) (*ExtractResponse, error)
	GenerateThumbnail(ctx context.Context, in *ThumbnailRequest, opts ...grpc.CallOption) (*ThumbnailResponse, error)
}

type oCREngineClient struct {
	cc grpc.ClientConnInterface
}

func NewOCREngineClient(cc grpc.ClientConnInterface) OCREngineClient {
	return &oCREngineClient{cc}
}

func (c *oCREngineClient) ExtractText(ctx context.Context, in *ExtractRequest, opts ...grpc.CallOption) (*ExtractResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExtractResponse)
	err := c.cc.Invoke(ctx, OCREngine_ExtractText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oCREngineClient) GenerateThumbnail(ctx context.Context, in *ThumbnailRequest, opts ...grpc.CallOption) (*ThumbnailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ThumbnailResponse)
	err := c.cc.Invoke(ctx, OCREngine_GenerateThumbnail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OCREngineServer is the server API for OCREngine service.
// All implementations must embed UnimplementedOCREngineServer
// for forward compatibility.
type OCREngineServer interface {
	ExtractText(context.Context, *ExtractRequest) (*ExtractResponse, error)
	GenerateThumbnail(context.Context, *ThumbnailRequest) (*ThumbnailResponse, error)
	mustEmbedUnimplementedOCREngineServer()
}

// UnimplementedOCREngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOCREngineServer struct{}

func (UnimplementedOCREngineServer) ExtractText(context.Context, *ExtractRequest) (*ExtractResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExtractText not implemented")
}
func (UnimplementedOCREngineServer) GenerateThumbnail(context.Context, *ThumbnailRequest) (*ThumbnailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateThumbnail not implemented")
}
func (UnimplementedOCREngineServer) mustEmbedUnimplementedOCREngineServer() {}
func (UnimplementedOCREngineServer) testEmbeddedByValue()                   {}

// UnsafeOCREngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OCREngineServer will
// result in compilation errors.
type UnsafeOCREngineServer interface {
	mustEmbedUnimplementedOCREngineServer()
}

func RegisterOCREngineServer(s grpc.ServiceRegistrar, srv OCREngineServer) {
	// If the following call panics, it indicates UnimplementedOCREngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OCREngine_ServiceDesc, srv)
}

func _OCREngine_ExtractText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OCREngineServer).ExtractText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OCREngine_ExtractText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OCREngineServer).ExtractText(ctx, req.(*ExtractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OCREngine_GenerateThumbnail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ThumbnailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OCREngineServer).GenerateThumbnail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OCREngine_GenerateThumbnail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OCREngineServer).GenerateThumbnail(ctx, req.(*ThumbnailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OCREngine_ServiceDesc is the grpc.ServiceDesc for OCREngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OCREngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ocr.OCREngine",
	HandlerType: (*OCREngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExtractText",
			Handler:    _OCREngine_ExtractText_Handler,
		},
		{
			MethodName: "GenerateThumbnail",
			Handler:    _OCREngine_GenerateThumbnail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ocr.proto",
}
